package dto;
// Generated May 22, 2019 4:10:30 PM by Hibernate Tools 4.3.1

import dto.common.IDTO;
import dto.common.IName;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderStatus generated by hbm2java
 */
@Entity
@Table(name = "order_status",
       catalog = "solarhubweb"
)
public class OrderStatus implements Serializable, IDTO, IName {
    public static OrderStatus CANCELLED = new OrderStatus(4,
                                                          "Huỷ");
    public static OrderStatus PENDING = new OrderStatus(1,
                                                        "Đang chờ");
    public static OrderStatus SHIPPED = new OrderStatus(3,
                                                        "Đã giao");
    public static OrderStatus SHIPPING = new OrderStatus(2,
                                                         "Đang giao");
    private long id;
    private String name;
    private Set<Order> orders;

    public OrderStatus() {
        this.orders = new HashSet<>(0);
    }

    public OrderStatus(long id,
                       String name) {
        this.orders = new HashSet<>(0);
        this.id = id;
        this.name = name;
    }

    public OrderStatus(long id,
                       String name,
                       Set<Order> orders) {
        this.orders = new HashSet<>(0);
        this.id = id;
        this.name = name;
        this.orders = orders;
    }

    @Id
    @Column(name = "Id",
            unique = true,
            nullable = false)
    @Override
    public long getId() {
        return this.id;
    }

    @Override
    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "Name",
            nullable = false)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY,
               mappedBy = "orderStatus")
    public Set<Order> getOrders() {
        return this.orders;
    }

    public void setOrders(Set<Order> orders) {
        this.orders = orders;
    }
}
