package dto;
// Generated May 22, 2019 4:10:30 PM by Hibernate Tools 4.3.1

import dto.common.IDTO;
import dto.common.IName;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role",
       catalog = "solarhubweb"
)
public class Role implements Serializable, IDTO, IName {
    private long id;
    private String name;
    private int priority;
    private Set<User> users;

    public Role() {
        this.users = new HashSet<>(0);
    }

    public Role(long id,
                String name,
                int priority) {
        this.users = new HashSet<>(0);
        this.id = id;
        this.name = name;
        this.priority = priority;
    }

    public Role(long id,
                String name,
                int priority,
                Set<User> users) {
        this.users = new HashSet<>(0);
        this.id = id;
        this.name = name;
        this.priority = priority;
        this.users = users;
    }

    @Id
    @Column(name = "Id",
            unique = true,
            nullable = false)
    @Override
    public long getId() {
        return this.id;
    }

    @Override
    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "Name",
            nullable = false)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "Priority",
            nullable = false)
    public int getPriority() {
        return this.priority;
    }

    public void setPriority(int priority) {
        this.priority = priority;
    }

    @OneToMany(fetch = FetchType.LAZY,
               mappedBy = "role")
    public Set<User> getUsers() {
        return this.users;
    }

    public void setUsers(Set<User> users) {
        this.users = users;
    }
}
