package dto;
// Generated May 22, 2019 4:10:30 PM by Hibernate Tools 4.3.1

import dto.common.IDTO;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderDetail generated by hbm2java
 */
@Entity
@Table(name = "order_detail",
       catalog = "toymanager"
)
public class OrderDetail implements Serializable, IDTO {
    private long id;
    private Order order;
    private Toy toy;
    private int quantity;
    private long totalPrice;

    public OrderDetail() {
    }

    public OrderDetail(long id,
                       Order order,
                       Toy toy,
                       int quantity,
                       long totalPrice) {
        this.id = id;
        this.order = order;
        this.toy = toy;
        this.quantity = quantity;
        this.totalPrice = totalPrice;
    }

    @Id
    @Column(name = "Id",
            unique = true,
            nullable = false)
    @Override
    public long getId() {
        return this.id;
    }

    @Override
    public void setId(long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OrderId",
                nullable = false)
    public Order getOrder() {
        return this.order;
    }

    public void setOrder(Order order) {
        this.order = order;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ToyId",
                nullable = false)
    public Toy getToy() {
        return this.toy;
    }

    public void setToy(Toy toy) {
        this.toy = toy;
    }

    @Column(name = "Quantity",
            nullable = false)
    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Column(name = "TotalPrice",
            nullable = false,
            precision = 10,
            scale = 0)
    public long getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(long totalPrice) {
        this.totalPrice = totalPrice;
    }
}
